"""Add MobileVerification table

Revision ID: 4e24bd9361e2
Revises: 2dbff6163ad8
Create Date: 2026-08-08 03:01:35.653589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e24bd9361e2'
down_revision: Union[str, None] = '2dbff6163ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_verifications_mobile_number'), 'mobile_verifications', ['mobile_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobile_verifications_mobile_number'), table_name='mobile_verifications')
    op.drop_table('mobile_verifications')
    # ### end Alembic commands ###
