"""Update products schema

Revision ID: 58c65fe22bff
Revises: 
Create Date: 2026-08-06 21:18:23.893708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c65fe22bff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('products', sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('products', sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('minimum_stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.drop_column('products', 'stock')
    op.drop_column('products', 'wholesale_price')
    op.drop_column('products', 'unit_price')
    op.drop_column('products', 'min_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('wholesale_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'minimum_stock')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'gst_percentage')
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
