"""Add owner_id to Category and Product

Revision ID: 5b1618b378ba
Revises: c64e4b89d69e
Create Date: 2026-08-07 00:20:33.852599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1618b378ba'
down_revision: Union[str, None] = 'c64e4b89d69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable=True
    op.add_column('categories', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.add_column('products', sa.Column('owner_id', sa.String(length=36), nullable=True))
    
    # 2. Get first user ID
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users LIMIT 1"))
    user = result.fetchone()
    
    if user:
        owner_id = user[0]
        connection.execute(sa.text(f"UPDATE categories SET owner_id = '{owner_id}' WHERE owner_id IS NULL"))
        connection.execute(sa.text(f"UPDATE products SET owner_id = '{owner_id}' WHERE owner_id IS NULL"))

    # 3. Alter column to nullable=False
    op.alter_column('categories', 'owner_id', nullable=False)
    op.alter_column('products', 'owner_id', nullable=False)

    # 4. Create foreign keys
    op.create_foreign_key(None, 'categories', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'owner_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'owner_id')
    # ### end Alembic commands ###
