"""Add shop_name to users

Revision ID: 9fd460e680ab
Revises: cf6bdefdf50e
Create Date: 2026-08-07 21:47:47.403658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd460e680ab'
down_revision: Union[str, None] = 'cf6bdefdf50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shop_name')
    # ### end Alembic commands ###
