"""make_product_fields_optional

Revision ID: c64e4b89d69e
Revises: 58c65fe22bff
Create Date: 2026-08-06 22:29:05.338161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64e4b89d69e'
down_revision: Union[str, None] = '58c65fe22bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'purchase_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'gst_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'minimum_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'minimum_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'gst_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('products', 'purchase_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
